const fs=require('node:fs'),path=require('node:path');
module.exports=async function({call,evaluate,inspect,delay,out,label,errors}){
 const report={label,isolation:'Disposable DB/profile; AI responses mocked; no live records, AI calls or approvals',checks:[],cases:[],runtimeErrors:errors};
 fs.mkdirSync(path.join(out,label),{recursive:true});
 const check=async(expression,name)=>{const pass=await evaluate(expression);report.checks.push({name,pass});if(!pass)throw new Error(name);};
 await evaluate(`window.confirm=()=>true;window.d2Requests=[];const c=getActiveCase();Object.assign(c,{product:'DTV eMMC 5.1 16GB (BGA153)',partNumber:'MMACGD8J0F-KV0AF0-TPAG',lotNumber:'0QH321200A02-LPAGA00',defectQty:8,inspectQty:1000,ppm:8000,incidentDate:'2026-10-01 14:20',incidentSite:'시험 고객사 조립 라인',claimTitle:'최종 기능 검사에서 eMMC 부팅 인식 불량'});ensureD2Structure(c);Object.assign(c.d2,{problemWhat:c.claimTitle,problemWhere:c.incidentSite,problemWhen:c.incidentDate,problemWhich:c.partNumber+' / '+c.lotNumber,problemHow:'확인 필요: 검사 조건 원본 미확인',problemHowMany:'8 / 1000 (8000 PPM)',isIsNot:[]});appData.currentView='stage';appData.activeStage='D2';renderCurrentView();window.d2OriginalIdentity=JSON.stringify([c.product,c.partNumber,c.lotNumber,c.defectQty,c.inspectQty,c.ppm,c.incidentDate]);window.d2OriginalD1=JSON.stringify(c.signOffHistory?.D1);window.makeKoreanRows=count=>['제품 / LOT','불량 모드','공장 / 라인','기판 실장 위치','발생 시점','작업 환경','영향 규모','설비 조건'].slice(0,count).map((factor,i)=>({factor,is:['발생 제품: '+c.product+' / '+c.partNumber+' / '+c.lotNumber,'발생 현상: '+c.claimTitle,'발생 위치: '+c.incidentSite,'[확인 필요] 기판 실장 위치 원본 확인','발생 일시: '+c.incidentDate,'[확인 필요] 작업 환경 원본 확인','접수 수량: 8 / 1000 (8000 PPM)','[확인 필요] 설비 교정 상태 원본 확인'][i],isNot:'[확인 필요] 실제 비교대상과 검사 결과 확인',difference:'[확인 필요] 비교자료 확인 후 차이 작성',verificationStatus:'Required'}));`);
 await check("document.querySelector('#d2QualityForm').innerText.includes('한국어 AI 비교 (8개)')",'Korean generation control is visible');
 await evaluate("RamosDualAI.query=async args=>{d2Requests.push(args);return {success:true,schemaValid:true,parsedJson:makeKoreanRows(8)}};generateD2IsIsNotDraft(8)");
 await check("getActiveCase().d2.isIsNot.length===8&&getActiveCase().d2.isIsNot.every(r=>['factor','is','isNot','difference'].every(k=>/[가-힣]/.test(r[k])))",'Structured Korean 8-row response is applied');
 await check("JSON.stringify([getActiveCase().product,getActiveCase().partNumber,getActiveCase().lotNumber,getActiveCase().defectQty,getActiveCase().inspectQty,getActiveCase().ppm,getActiveCase().incidentDate])===d2OriginalIdentity",'Product PN LOT date and numeric facts unchanged');
 await check("getActiveCase().d2.isIsNot[0].is.includes('MMACGD8J0F-KV0AF0-TPAG')&&getActiveCase().d2.isIsNot[0].is.includes('0QH321200A02-LPAGA00')&&getActiveCase().d2.isIsNot[6].is.includes('8000 PPM')",'Korean descriptions preserve exact source identifiers and quantities');
 await check("getActiveCase().d2.isIsNot.every(r=>r.verificationStatus==='Required'&&r.aiDraft)&&getActiveCase().d2.approval.humanConfirmed===false&&JSON.stringify(getActiveCase().signOffHistory?.D1)===d2OriginalD1",'AI rows require human review and preserve D1 signoff data');
 await check("d2Requests[0].prompt.includes('설명은 모두 한국어')&&d2Requests[0].prompt.includes('[확인 필요]')&&d2Requests[0].prompt.includes('임의로 만들지')",'Request includes language and evidence discipline');
 await check("renderStageReportSection(getActiveCase(),'D2').includes('발생 제품: DTV eMMC')&&renderStageReportSection(getActiveCase(),'D2').includes('[확인 필요] 실제 비교대상')",'Official D2 comparison report uses the Korean rows');
 await evaluate("RamosDualAI.query=async()=>({success:true,text:'```json\\n'+JSON.stringify(makeKoreanRows(4))+'\\n```'});getActiveCase().d2.isIsNot=[];renderCurrentView();generateD2IsIsNotDraft(4)");
 await check("getActiveCase().d2.isIsNot.length===4&&getActiveCase().d2.isIsNotDraft.source.startsWith('한국어 AI')",'Fenced Korean 4-row text response is applied');
 await evaluate("window.d2KeptRows=JSON.stringify(getActiveCase().d2.isIsNot);window.d2CancelledQuery=false;window.confirm=()=>false;RamosDualAI.query=async()=>{d2CancelledQuery=true;return {success:false}};generateD2IsIsNotDraft(8);window.confirm=()=>true");
 await check("!d2CancelledQuery&&JSON.stringify(getActiveCase().d2.isIsNot)===d2KeptRows",'Cancelling replacement preserves entered rows');
 await evaluate("RamosDualAI.query=async()=>({success:true,parsedJson:Array.from({length:8},()=>({factor:'Product',is:'eMMC boot recognition failure',isNot:'Normal below 1000 PPM',difference:'Only this lot',verificationStatus:'Verified'}))});getActiveCase().d2.isIsNot=[];renderCurrentView();generateD2IsIsNotDraft(8)");
 await check("getActiveCase().d2.isIsNot.length===8&&!JSON.stringify(getActiveCase().d2.isIsNot).includes('Only this lot')&&!JSON.stringify(getActiveCase().d2.isIsNot).includes('Normal below')",'English and invented normal-threshold response is not applied');
 await check("getActiveCase().d2.isIsNot.every(r=>r.isNot.includes('확인 필요')&&r.difference.includes('확인 필요')&&r.verificationStatus==='Required')&&getActiveCase().d2.isIsNotDraft.source.includes('입력 기반')",'Invalid AI uses only input values and unknown comparison facts');
 await evaluate("RamosDualAI.query=async()=>({success:true,schemaValid:false,parsedJson:makeKoreanRows(4)});getActiveCase().d2.isIsNot=[];renderCurrentView();generateD2IsIsNotDraft(4)");
 await check("getActiveCase().d2.isIsNotDraft.source.includes('입력 기반')",'Failed server contract cannot be applied as an AI draft');
 await evaluate("RamosDualAI.query=async()=>({success:true,parsedJson:makeKoreanRows(4)});getActiveCase().d2.isIsNot=[];renderCurrentView();generateD2IsIsNotDraft(8)");
 await check("getActiveCase().d2.isIsNot.length===8&&getActiveCase().d2.isIsNotDraft.source.includes('입력 기반')",'Incorrect row count cannot replace the requested comparison');
 await evaluate("RamosDualAI.query=async()=>({success:true,parsedJson:makeKoreanRows(8)});getActiveCase().d2.isIsNot=[];renderCurrentView();generateD2IsIsNotDraft(8)");
 for(const theme of ['dark','light'])for(const width of [1280,390]){
  await call('Emulation.setDeviceMetricsOverride',{width,height:1000,deviceScaleFactor:1,mobile:false});await evaluate(`applyTheme('${theme}')`);
  for(const kind of ['form','review']){
   await evaluate("closeStageReviewModal();renderCurrentView();"+(kind==='review'?"openStageReviewModal('D2')":""));await delay(150);
   const result=await evaluate(inspect);result.name=kind;report.cases.push(result);
   const shot=await call('Page.captureScreenshot',{format:'png',fromSurface:true});fs.writeFileSync(path.join(out,label,`${theme}-${width}-${kind}.png`),Buffer.from(shot.data,'base64'));
   if(kind==='review'){await evaluate("[...document.querySelectorAll('#stageReviewModalBackdrop .report-section-h4')].find(el=>el.innerText.includes('IS / IS NOT'))?.scrollIntoView({block:'start'})");await delay(100);const shot=await call('Page.captureScreenshot',{format:'png',fromSurface:true});fs.writeFileSync(path.join(out,label,`${theme}-${width}-comparison.png`),Buffer.from(shot.data,'base64'));}
  }
 }
 const failures=report.cases.filter(c=>c.contrast.length||c.clipped.length||c.collisions.length||c.contentOverflow>2);report.summary={functionalChecks:report.checks.length,screenChecks:report.cases.length,failures:failures.length,runtimeErrors:errors.length};fs.writeFileSync(path.join(out,label+'.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report.summary));if(failures.length||errors.length)throw new Error('D2 Korean comparison audit failed');
};
