/* Real authenticated registration/reply/closure in a disposable server and Edge. */
const fs=require('node:fs'),path=require('node:path');
module.exports=async({call,evaluate,inspect,delay,out,label,errors})=>{
 const report={label,isolation:'Disposable DB/profile; no production notices, approvals, email or AI',checks:[],cases:[],runtimeErrors:errors};
 const check=async(code,name)=>{if(!await evaluate(code))throw Error(name);report.checks.push(name)};
 const wait=async code=>{for(let i=0;i<100;i++){if(await evaluate(code))return;await delay(100)}throw Error('Wait: '+code)};
 await evaluate("saveAppData=()=>{};persistCurrentEditor=()=>true;switchNav('supplier-notices');window.noticeInitialState=null");
 await wait("document.querySelector('#supplierNoticeTable')?.innerText.includes('등록된 외주사')");
 await evaluate("(async()=>{noticeInitialState=(await QMSApi.request('/__api__/qms/state')).record})()");
 const initialState=await evaluate('noticeInitialState');
 await check("document.getElementById('menuCatSupplierQuality').textContent==='외주 품질 관리'&&document.getElementById('nav-supplier-notices').classList.contains('active')",'third supplier navigation grouped and selected');
 async function screens(name){for(const theme of ['light','dark'])for(const width of [1600,1280,768,390]){await call('Emulation.setDeviceMetricsOverride',{width,height:1000,deviceScaleFactor:1,mobile:false});await evaluate(`applyTheme('${theme}');closeNavigationMenu()`);await delay(100);const r=await evaluate(inspect);r.name=name;report.cases.push(r);}fs.writeFileSync(path.join(out,label+'_progress.json'),JSON.stringify(report,null,2));}
 await screens('empty-register');
 await evaluate("supplierNoticeNew()");await screens('new-notice');
 await evaluate(`(()=>{const f=document.getElementById('supplierNoticeForm');for(const [key,value]of Object.entries({supplierId:'SUP-TECHL',title:'수신 및 회신 확인용 eMMC 부적합',department:'품질혁신팀',owner:'UI 점검 담당자',site:'TechL Vina',occurredAt:'2026-10-02T09:30',dueDate:'2026-10-05',product:'eMMC 16GB 화면 점검 제품',partNumber:'KEEP-PN-012345678901234567890123456789',lotNo:'KEEP-LOT-012345678901234567890123456789',description:'확인된 부팅 현상 <img src=x onerror=window.NOTICE_XSS=1>\\n원본 자료 대조 요청',requestedAction:'봉쇄 범위와 원본 분석 자료 회신 요청'}))f.elements.namedItem(key).value=value;const d=new DataTransfer();d.items.add(new File(['source evidence bytes'],'통보 근거 원본.txt',{type:'text/plain'}));f.elements.namedItem('evidence').files=d.files;supplierNoticeCapture(f);return handleSupplierNoticeSubmit({preventDefault(){},target:f});})()`);
 await wait("document.querySelector('.iq-card-heading')?.innerText.includes('통보 대기')");
 await evaluate("(async()=>{window.noticeRecord=(await QMSApi.request('/__api__/qms/supplier-notices')).items[0];window.noticeId=noticeRecord.ticketId;})()");
 const id=await evaluate('noticeId');
 await check("noticeRecord.supplier.username==='thkwon'&&noticeRecord.createdBy.username==='sjkim'&&noticeRecord.inputQty===null&&noticeRecord.partNumber==='KEEP-PN-012345678901234567890123456789'&&noticeRecord.status==='Draft'",'real author official recipient and source identifiers; no automatic publication');
 await check("!window.NOTICE_XSS&&!document.querySelector('#mainContentContainer img')&&document.querySelector('#mainContentContainer').innerText.includes('<img src=x')",'notice HTML safe visible text');
 await screens('draft-detail');
 await evaluate("supplierNoticeEdit(noticeId)");await check("document.querySelector('[name=supplierId]').value==='SUP-TECHL'&&document.querySelector('[name=partNumber]').value===noticeRecord.partNumber",'draft edit restored');await evaluate("supplierNoticeOpen('detail',noticeId)");
 await evaluate("(()=>{const f=document.getElementById('supplierNoticeManageForm');f.elements.namedItem('action').value='publish';f.elements.namedItem('owner').value='변경한 실제 담당자';f.elements.namedItem('comment').value='해당 업체에 통보 공개 및 회신 요청';return handleSupplierNoticeManage({preventDefault(){},target:f})})()");
 await wait("document.querySelector('.iq-card-heading')?.innerText.includes('회신 대기')");await screens('issued-detail');
 await check("document.querySelector('#mainContentContainer').innerText.includes('변경한 실제 담당자')",'management fields retained when publishing');
 await evaluate("handleQuickLogin('thkwon')");await wait("CURRENT_USER?.username==='thkwon'&&window.QMS_APP_READY===true");await evaluate("switchNav('supplier-notices')");await wait("document.querySelector('#supplierNoticeTable')?.innerText.includes(noticeId)");
 await check("!document.querySelector('[onclick=\"supplierNoticeNew()\"]')&&document.querySelector('#internalCompanyNavSection').style.display==='none'",'supplier receives own notice and cannot create company notices');
 await evaluate("supplierNoticeOpen('detail',noticeId)");await screens('supplier-reply-form');
 await check("document.getElementById('supplierNoticeReplyForm')&&!document.getElementById('supplierNoticeManageForm')",'supplier reply form without internal review actions');
 await evaluate("(async()=>{const a=document.querySelector('.iq-file-list a');const response=await fetch(a.getAttribute('href'));window.sourceDownloaded=await response.text()})()");await check("sourceDownloaded==='source evidence bytes'",'supplier downloads exact original');
 await evaluate("(()=>{const f=document.getElementById('supplierNoticeReplyForm');f.elements.namedItem('responseSummary').value='봉쇄 범위 확인 및 측정 원본 회신';f.elements.namedItem('correctiveAction').value='분석 결과 검토 요청';const d=new DataTransfer();d.items.add(new File(['reply measurement bytes'],'외주사 회신 원본.txt',{type:'text/plain'}));f.elements.namedItem('evidence').files=d.files;return handleSupplierNoticeReply({preventDefault(){},target:f})})()");
 await wait("document.querySelector('.iq-card-heading')?.innerText.includes('회신 접수')");await check("document.querySelector('#mainContentContainer').innerText.includes('외주사 직접 회신')&&document.querySelector('#mainContentContainer').innerText.includes('권태훈')",'real supplier reply recorded separately');
 await screens('supplier-response-detail');
 for(const username of ['yspark','sangwook.ki','ojs']){
  await evaluate(`handleQuickLogin('${username}')`);await wait(`CURRENT_USER?.username==='${username}'&&window.QMS_APP_READY===true`);await evaluate("switchNav('supplier-notices')");await wait("document.querySelector('#supplierNoticeTable')?.innerText.includes('공개된 부적합 통보가 없습니다')");
  await check("!document.querySelector('#mainContentContainer').innerText.includes(noticeId)",username+' sees no other company notice');
 }
 await evaluate("handleQuickLogin('sjkim')");await wait("CURRENT_USER?.username==='sjkim'&&window.QMS_APP_READY===true");await evaluate("switchNav('supplier-notices')");await wait("document.querySelector('#supplierNoticeTable')?.innerText.includes(noticeId)");await evaluate("supplierNoticeOpen('detail',noticeId)");
 await check("document.getElementById('supplierNoticeReplyForm')?.querySelector('[name=responseSource]')",'manual response path explicitly identifies internal recorder');
 await evaluate("(()=>{const f=document.getElementById('supplierNoticeReplyForm');f.closest('details').open=true;f.elements.namedItem('responseSummary').value='추가 이메일 회신을 사내 담당자가 기록';f.elements.namedItem('responseReceivedAt').value='2026-10-02T11:45';return handleSupplierNoticeReply({preventDefault(){},target:f})})()");
 await check("document.querySelector('#mainContentContainer').innerText.includes('이메일 회신 사내 기록')&&document.querySelector('#mainContentContainer').innerText.includes('추가 이메일 회신')",'manual response recorded with real internal author');

 await evaluate("(()=>{const f=document.getElementById('supplierNoticeManageForm');f.elements.namedItem('action').value='review';f.elements.namedItem('comment').value='품질 담당자 회신 검토 시작';return handleSupplierNoticeManage({preventDefault(){},target:f})})()");await wait("document.querySelector('.iq-card-heading')?.innerText.includes('회신 검토 중')");await screens('review-detail');
 await evaluate("(()=>{const f=document.getElementById('supplierNoticeManageForm');f.elements.namedItem('action').value='close';f.elements.namedItem('comment').value='종결 검토';return handleSupplierNoticeManage({preventDefault(){},target:f})})()");
 await check("document.getElementById('supplierNoticeManageForm').querySelector('.iq-error').innerText.includes('검증')&&document.querySelector('.iq-card-heading').innerText.includes('검토 중')",'closure without real validation remains in review');
 await evaluate("(()=>{const f=document.getElementById('supplierNoticeManageForm');f.elements.namedItem('validationResult').value='회신 측정 원본과 대조하여 화면 시험 검증';return handleSupplierNoticeManage({preventDefault(){},target:f})})()");await wait("document.querySelector('.iq-card-heading')?.innerText.includes('종결')");await screens('closed-detail');
 await check("document.querySelector('#mainContentContainer').innerText.includes('종결 검증 결과')&&document.querySelector('#mainContentContainer').innerText.includes('김성중')",'closure attributed to authenticated quality user');
 await evaluate("supplierNoticeOpen('list');const f=document.querySelector('.iq-filters');f.elements.namedItem('search').value='NOT-MATCH';supplierNoticeFilter(f)");await check("document.getElementById('supplierNoticeTable').innerText.includes('조건에 맞는')",'search filters records');await evaluate("resetSupplierNoticeFilters()");
 await call('Page.reload',{ignoreCache:true});await delay(250);await wait('window.QMS_APP_READY===true');await evaluate(`window.noticeId=${JSON.stringify(id)};window.noticeInitialState=${JSON.stringify(initialState)};saveAppData=()=>{};persistCurrentEditor=()=>true;switchNav('supplier-notices')`);await wait("document.querySelector('#supplierNoticeTable')?.innerText.includes(noticeId)");
 await check("document.getElementById('supplierNoticeTable').innerText.includes('종결')",'central notice and status persist through reload');
 await check("(async()=>{const s=(await QMSApi.request('/__api__/qms/state')).record;return s.revision===noticeInitialState.revision&&s.stateHash===noticeInitialState.stateHash})()",'notice workflow never changes customer state');
 const failures=report.cases.filter(r=>r.contrast.length||r.clipped.length||r.collisions.length||r.contentOverflow>2||r.mainOverflow>2);report.summary={functionalChecks:report.checks.length,screenChecks:report.cases.length,failures:failures.length,runtimeErrors:errors.length};fs.writeFileSync(path.join(out,label+'.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report.summary));if(failures.length||errors.length)throw Error('Notice UI issues '+failures.map(r=>r.theme+'/'+r.width+'/'+r.name).join(', '));
 if(process.env.QMS_AUDIT_NOTICE_SHOT){fs.mkdirSync(path.join(out,label),{recursive:true});await call('Emulation.setDeviceMetricsOverride',{width:1280,height:1000,deviceScaleFactor:1,mobile:false});await evaluate("applyTheme('light');supplierNoticeOpen('detail',noticeId)");await delay(300);const shot=await call('Page.captureScreenshot',{format:'png',fromSurface:true,captureBeyondViewport:false});fs.writeFileSync(path.join(out,label,'light-1280-detail.png'),Buffer.from(shot.data,'base64'));}
};
