const fs=require('node:fs'),path=require('node:path');
module.exports=async function({call,evaluate,inspect,delay,root,out,label,errors}) {
 const report={label,isolation:'Disposable server/browser, synthetic presentation records, saves disabled; no AI or approval actions',cases:[],headings:[],metrics:[],runtimeErrors:errors};
 const agents=['Intake Orchestrator','Evidence Agent','Evidence Agent','Evidence Agent','Triage Agent','Evidence Agent','Triage Agent','Containment Agent'];
 const units=['NATURAL_LANGUAGE_INTERPRETATION','DOCUMENT_COLLECTION','STANDARDIZATION','DATA_VALIDATION','AGGREGATION','CROSS_CHECK','RISK_AND_POLICY','GENERATION'];
 const runs=[{id:701,requestText:'UI-TEST-0001 D1~D3 초안을 작성해줘 · 아주 긴 요청도 전체 내용을 확인할 수 있는지 점검합니다.',requestedBy:'ui-test@example.invalid',intent:'CREATE_D1_D3_DRAFT',status:'AWAITING_APPROVAL',riskLevel:'MEDIUM',updatedAt:'2026-10-02T10:40:00',policyVersion:'QMS-POLICY-1',modelContractVersion:'AGENT-OUTPUT-1',caseRevision:5,retryCount:0,result:{summary:'등록된 Case와 원본 자료를 대조한 화면 점검 표시입니다.',facts:['화면 점검 사실'],inferences:[],unknowns:['미확인 원인은 확정하지 않습니다.'],confidenceScore:0.75},steps:agents.map((agentName,i)=>({agentName,unitOperation:units[i],status:'COMPLETED',startedAt:'2026-10-02T10:40:00',completedAt:'2026-10-02T10:40:00'}))},...['COMPLETED','NEEDS_HUMAN','FAILED','RETRY_SCHEDULED'].map((status,i)=>({id:702+i,requestText:'긴 품번·LOT를 포함한 자료 검토 화면 점검 '+i,intent:'VALIDATE_CASE',requestedBy:'ui-test@example.invalid',status,riskLevel:i?'HIGH':'LOW',updatedAt:'2026-10-02T10:41:00',result:{},steps:[]}))];
 await evaluate(`QMSApi.listAgentRuns=async()=>${JSON.stringify(runs)};QMSApi.listQualityFindings=async()=>[{id:1,runId:701,severity:'CRITICAL',status:'OPEN',code:'LONG_ORIGINAL_REQUIRED',field:'d2.problemWhich',description:'긴 제품명과 품번·LOT는 원본을 확인하고 담당자가 직접 판단해야 합니다. 이 항목은 화면 점검용입니다.'}];QMSApi.listAgentSources=async()=>[{id:1,sourceType:'Customer Report',originalName:'고객_eMMC_부적합_현상과_측정_자료_아주_긴_파일명_점검용_원본_Report_20261002.pdf',extractionStatus:'Human review',sha256:'abcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdef'}];QMSApi.listAgentNotifications=async()=>[{id:1,runId:701,caseId:'UI-TEST-0001',severity:'WARNING',title:'담당자 확인이 필요한 시험 알림',message:'이것은 화면 확인용입니다.'}];QMSApi.getAgentAdapters=async()=>({internalSystems:{available:false,provider:'UNCONFIGURED'},email:{provider:'UNDECIDED'},externalInformation:{available:false,provider:'UNCONFIGURED'}});getActiveCase().product='DTV eMMC 5.1 16GB (BGA153) · 긴 제품 상세명 화면 점검';getActiveCase().partNumber='MMACGD8J0F-KV0AF0-TPAG-UI-LONG-PART-NUMBER';getActiveCase().lotNumber='0QH321200A02-LPAGA00-UI-LONG-LOT-NUMBER';for(const key of ['product','partNumber','lotNumber'])appData.intakeQueue[0][key]=getActiveCase()[key];getActiveCase().evidenceList=[{id:'UI-ONLY-METADATA',title:'화면 점검 원본',file:'화면_점검용_원본_실제첨부아님.pdf',type:'Metadata only',linkedStages:['D2']}];`);
 const views=[['dashboard',"switchNav('dashboard')"],['cases-list',"switchNav('cases-list')"],['new-case',"switchNav('new-case')"],['triage',"switchNav('intake-triage')"],['agent',"switchNav('agent-operations');refreshAgentOperations()"],['supplier',"switchNav('supplier-portal');switchSupplierTab('watchtower')"],['supplier-pcn',"switchNav('supplier-portal');switchSupplierTab('intake');setSupplierTicketType('PCN')"],['supplier-issue',"switchNav('supplier-portal');switchSupplierTab('intake');setSupplierTicketType('Issue')"],['evidence',"switchNav('evidence-hub')"],['actions',"switchNav('actions-hub')"],['reports',"switchNav('reports-hub')"],['mission',"switchNav('mission-control')"],...['overview','D1','D2','D3','D4','D5','D6','D7','D8'].map(stage=>['stage-'+stage,`appData.currentView='stage';appData.activeStage='${stage}';renderCurrentView()`])];
 const popups=[['notification',"switchNav('dashboard');openNotificationModal()"],['supplier-detail',"switchNav('supplier-portal');openSupplierTicketModal(loadSupplierRecords()[0].ticketId)"],['sla',"switchNav('dashboard');openSlaTimelineModal()"],['ai',"switchNav('dashboard');openAIAssistantModal()"],['source',"switchNav('agent-operations');openAgentSourceModal()"],['audit',"switchNav('reports-hub');openCustomerAiGatekeeperModal(null,'gate3D')"],...['D1','D2','D3','D4','D5','D6','D7','D8'].map(stage=>['review-'+stage,`appData.currentView='stage';appData.activeStage='${stage}';renderCurrentView();openStageReviewModal('${stage}')`])];
 fs.mkdirSync(path.join(out,label),{recursive:true});
 const capture=async(name,code,theme,width,isPage)=>{
  if(process.env.QMS_DESIGN_VIEWS&&!process.env.QMS_DESIGN_VIEWS.split(',').includes(name))return;
  await evaluate("closeStageReviewModal();closeDocumentViewer();closeModal();closeNavigationMenu();"+code);await delay(150);
  const result=await evaluate(inspect);result.name=name;report.cases.push(result);
  if(isPage){const meta=await evaluate("(()=>{const h=document.querySelector('.qms-page-header'),title=h?.querySelector('h1'),icon=h?.querySelector('.qms-page-icon'),s=h&&getComputedStyle(h);return h&&title&&icon?{leadHeight:h.querySelector('.qms-page-lead').getBoundingClientRect().height,leadContentHeight:Math.max(h.querySelector('.qms-page-copy').getBoundingClientRect().height,icon.getBoundingClientRect().height),direction:s.flexDirection,radius:s.borderRadius,bg:s.backgroundColor,padding:s.padding,titleSize:getComputedStyle(title).fontSize,titleFont:getComputedStyle(title).fontFamily,titleWeight:getComputedStyle(title).fontWeight,iconW:icon.getBoundingClientRect().width,iconBg:getComputedStyle(icon).backgroundColor,bodyWidth:(()=>{const m=document.getElementById('mainContentContainer'),st=getComputedStyle(m);return m.clientWidth-parseFloat(st.paddingLeft)-parseFloat(st.paddingRight)})(),headerWidth:h.getBoundingClientRect().width}:null})()");report.headings.push({name,theme,width,...meta});if(!meta||Math.abs(meta.bodyWidth-meta.headerWidth)>2||meta.leadHeight>meta.leadContentHeight+2||meta.direction!=='row')report.headings.at(-1).invalid=true;}
  if(['agent','supplier'].includes(name)){const metrics=await evaluate("[...document.querySelectorAll('.qms-metric-card')].map(el=>({radius:getComputedStyle(el).borderRadius,padding:getComputedStyle(el).padding,label:getComputedStyle(el.querySelector('.qms-metric-label')).fontSize,value:getComputedStyle(el.querySelector('.qms-metric-value')).fontSize,note:getComputedStyle(el.querySelector('.qms-metric-note')).fontSize}))");report.metrics.push({name,theme,width,metrics});}
  if(['agent','supplier','triage','stage-D1','stage-D2','source','review-D1'].includes(name)&&[1600,390].includes(width)){const shot=await call('Page.captureScreenshot',{format:'png',fromSurface:true});fs.writeFileSync(path.join(out,label,`${theme}-${width}-${name}.png`),Buffer.from(shot.data,'base64'));}
  fs.writeFileSync(path.join(out,label+'.json'),JSON.stringify(report,null,2));
 };
 for(const theme of ['dark','light'])for(const width of [1600,1280,1024,768,390]){
  await call('Emulation.setDeviceMetricsOverride',{width,height:1000,deviceScaleFactor:1,mobile:false});await evaluate(`applyTheme('${theme}')`);
  for(const [name,code]of views)await capture(name,code,theme,width,true);
  for(const [name,code]of popups)await capture(name,code,theme,width,false);
  console.log(theme+'/'+width+' pages and populated dialogs checked');
 }
 for(const theme of ['dark','light'])for(const width of [1600,1280,1024,768,390]){
  const rows=report.headings.filter(s=>s.theme===theme&&s.width===width);if(rows.some(s=>s.invalid))throw new Error('Page heading width mismatch: '+JSON.stringify(rows.filter(s=>s.invalid)));
  if(new Set(rows.map(s=>JSON.stringify([s.radius,s.bg,s.padding,s.titleSize,s.titleFont,s.titleWeight,s.iconW,s.iconBg]))).size!==1)throw new Error('Page heading composition varies: '+theme+'/'+width);
  const metrics=report.metrics.filter(s=>s.theme===theme&&s.width===width).flatMap(s=>s.metrics);
  if(new Set(metrics.map(m=>JSON.stringify(m))).size!==1)throw new Error('Agent and supplier metrics vary: '+theme+'/'+width);
 }
 const failures=report.cases.filter(c=>c.contrast.length||c.clipped.length||c.collisions.length||c.contentOverflow>2);report.summary={checked:report.cases.length,failures:failures.length,runtimeErrors:errors.length,headingComparisons:report.headings.length,metricGroups:report.metrics.length};fs.writeFileSync(path.join(out,label+'.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report.summary));if(report.cases.some(c=>c.small.length))throw new Error('Small text persists: '+JSON.stringify(report.cases.filter(c=>c.small.length).map(c=>({theme:c.theme,width:c.width,name:c.name,small:c.small}))));if(failures.length||errors.length)throw new Error('UI design audit failed: '+failures.map(c=>c.theme+'/'+c.width+'/'+c.name).join(', '));
};
